import os
import sys
import json
from pathlib import Path
import numpy as np
import matplotlib
# Force Matplotlib to use the headless 'Agg' backend for cluster compatibility
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

# Automatically manage internal paths
src_path = Path(__file__).resolve().parent.parent
if str(src_path) not in sys.path:
    sys.path.insert(0, str(src_path))

class QwenLayoutVisualizer:
    def __init__(self, output_dir: str, snapshot_dir: str):
        self.output_root = Path(output_dir)
        self.snapshot_root = Path(snapshot_dir)
        self.snapshot_root.mkdir(parents=True, exist_ok=True)
        
        # Find all JSON output files generated by Qwen
        self.json_files = sorted(list(self.output_root.glob("*.json")))
        if not self.json_files:
            raise FileNotFoundError(f"No generated layout JSON files found in {output_dir}")
            
        print(f"Found {len(self.json_files)} custom layouts to render.")

    def _draw_cube_edges(self, ax, bmin, bmax, color, label):
        """Draws the wireframe outline of an axis-aligned bounding box."""
        # Generate the 8 corners of the 3D box
        corners = np.array([
            [bmin[0], bmin[1], bmin[2]],
            [bmax[0], bmin[1], bmin[2]],
            [bmax[0], bmax[1], bmin[2]],
            [bmin[0], bmax[1], bmin[2]],
            [bmin[0], bmin[1], bmax[2]],
            [bmax[0], bmin[1], bmax[2]],
            [bmax[0], bmax[1], bmax[2]],
            [bmin[0], bmax[1], bmax[2]]
        ])
        
        # Define the 12 edges connecting those corners
        edges = [
            (0,1), (1,2), (2,3), (3,0), # Bottom face
            (4,5), (5,6), (6,7), (7,4), # Top face
            (0,4), (1,5), (2,6), (3,7)  # Vertical pillars
        ]
        
        # Plot each edge line. Only apply the label once to avoid duplicating legend items.
        for i, edge in enumerate(edges):
            lbl = label if i == 0 else "_"
            ax.plot3D(
                [corners[edge[0], 0], corners[edge[1], 0]],
                [corners[edge[0], 1], corners[edge[1], 1]],
                [corners[edge[0], 2], corners[edge[1], 2]],
                color=color, linewidth=2, label=lbl
            )
            
        # Optional: Add a subtle, semi-transparent filled surface to make it look solid
        x = [bmin[0], bmax[0]]
        y = [bmin[1], bmax[1]]
        z = [bmin[2], bmax[2]]
        ax.bar3d(bmin[0], bmin[1], bmin[2], 
                 bmax[0]-bmin[0], bmax[1]-bmin[1], bmax[2]-bmin[2], 
                 color=color, alpha=0.1)

    def render_layout(self, json_path: Path):
        print(f"Processing: {json_path.name}...")
        with json_path.open("r", encoding="utf-8") as file:
            data = json.load(file)
            
        category = data.get("category", "Unknown")
        parts = data.get("parts", [])
        
        # Create a clean Matplotlib 3D Canvas
        fig = plt.figure(figsize=(10, 8))
        ax = fig.add_subplot(111, projection='3d')
        
        # Generate an array of distinct colors for the part labels
        unique_labels = sorted(list(set(part["label"] for part in parts)))
        color_palette = plt.cm.get_cmap("tab20", len(unique_labels))
        label_to_color = {label: color_palette(i) for i, label in enumerate(unique_labels)}
        
        # Iterate over Qwen's parts collection and plot them
        for part in parts:
            part_id = part["id"]
            label = part["label"]
            bbox = part["bbox"]
            
            bmin = bbox["min"]
            bmax = bbox["max"]
            
            color = label_to_color[label]
            self._draw_cube_edges(ax, bmin, bmax, color, label=f"{label} ({part_id})")
            
        # Configure axis boundaries exactly to your [-0.5, 0.5] unit cube space specifications
        ax.set_xlim([-0.5, 0.5])
        ax.set_ylim([-0.5, 0.5])
        ax.set_zlim([-0.5, 0.5])
        
        # Labelling axes according to your Z-up orientation properties
        ax.set_xlabel("X Axis")
        ax.set_ylabel("Y Axis")
        ax.set_zlabel("Z Axis (Up)")
        
        ax.set_title(f"Qwen Proposed Layout: {category}\n({json_path.stem})", fontsize=12, fontweight='bold')
        
        # Build the descriptive semantic label legend side panel
        ax.legend(loc='center left', bbox_to_anchor=(1.05, 0.5), title="Semantic Parts Layout")
        
        # Adjust layout spacing to accommodate the legend safely without clipping
        plt.tight_layout()
        
        # 1. Clear out all previous snapshots from the folder to avoid clutter
        old_snapshots = self.snapshot_root.glob("*.png")
        for file in old_snapshots:
            file.unlink()  # Deletes the file instantly
        print(f"🧹 Cleaned up previous snapshots in {self.snapshot_root.name}/")


        camera_angles = {
            "perspective": (20, -45), # Classic 3D isometric view
            "top": (90, -90),         # Bird's-eye layout blueprint view
            "side": (0, 0),          # Straight-on elevation profile view
            "front": (0, -90),          # Straight-on elevation profile view
            "isometric_rear": (30, 135)          # Straight-on elevation profile view
        }
        
        # Loop through each perspective and capture a snapshot
        for angle_name, (elev, azim) in camera_angles.items():
            # Adjust the camera viewport matrix
            ax.view_init(elev=elev, azim=azim)
            
            # Generate a distinct filename specifying the angle
            output_image_path = self.snapshot_root / f"render_{json_path.stem}_{angle_name}.png"
            
            plt.savefig(output_image_path, dpi=150, bbox_inches='tight')
            print(f"🎉 Saved {angle_name} snapshot to: {output_image_path.name}")
            
        plt.close()

    def render_all(self):
        for json_file in self.json_files:
            try:
                self.render_layout(json_file)
            except Exception as e:
                print(f"Skipping rendering file {json_file.name} due to error: {e}")

if __name__ == "__main__":
    import argparse
    
    OUTPUT_DIR = "/rhome/jankula/ML3D_project/project6_qwen_pipeline/src/outputs"
    SNAPSHOT_DIR = "/rhome/jankula/ML3D_project/project6_qwen_pipeline/src/project6_qwen_pipeline/rendered_snapshots"
    
    # 1. Set up terminal argument parser
    parser = argparse.ArgumentParser(description="Render specific Qwen JSON layouts.")
    parser.add_argument(
        "--file", 
        type=str, 
        default=None, 
        help="Specific JSON filename to render (e.g. layout_sofa.json). If omitted, renders the newest file."
    )
    args = parser.parse_args()

    # 2. Initialize visualizer class
    visualizer = QwenLayoutVisualizer(OUTPUT_DIR, SNAPSHOT_DIR)
    
    # 3. Choose execution path based on input
    if args.file:
        # User specified a file
        target_path = Path(OUTPUT_DIR) / args.file
        if not target_path.exists():
            print(f"❌ Error: The file '{args.file}' does not exist inside {OUTPUT_DIR}")
            print("Available files:")
            for f in sorted(list(Path(OUTPUT_DIR).glob("*.json"))):
                print(f" - {f.name}")
        else:
            visualizer.render_layout(target_path)
    else:
        # No file specified -> Automatically grab the absolute newest creation!
        all_json_files = list(Path(OUTPUT_DIR).glob("*.json"))
        if not all_json_files:
            print("❌ No JSON output layouts found.")
        else:
            # Sort files by their file modification time (most recent first)
            all_json_files.sort(key=lambda x: x.stat().st_mtime, reverse=True)
            newest_file = all_json_files[0]
            
            print(f"💡 No file specified. Automatically rendering the most recent layout creation...")
            visualizer.render_layout(newest_file)